# run the python script at scripts/main.py then commit the changes to the repo

name: Rebuild Database

on:
  schedule:
    # Run at midnight on the first of every month
    - cron: '0 0 1 * *'

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run : |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
          python scripts/main.py
      - name: Commit files
        run: |
          git config --local user.email "bot@gusberinger.com"
          git config --local user.name "Gus Beringer (bot)"
          git add .
          git commit -m "Rebuild database on $(date -u)"