# run the python script at scripts/main.py then commit the changes to the repo

name: Rebuild Database

on:
  schedule:
    # Run at midnight on the first of every month
    - cron: '0 0 1 * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run : |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
          python scripts/main.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "rebuilt database on date ${{ github.event.scheduled_execution_time }}"
