name: Code Quality Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: git lfs pull

      - uses: actions/checkout@v3
      - name: NPM
        run : |
          npm install
          npm run lint
          npm run type-check
          npm run build
          npm run format