name: Automatic Database Update

on:
  schedule:
    - cron: '0 0 */3 * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12' 
      - name: Add Environment Files
        run: |
          echo "${{ secrets.WRANGLER_TOML }}" > wrangler.toml
      - name: Database Update
        run : |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
          python scripts/main.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "automatic database update"
